### ISSUE TITLE
Store Features must be removed

### ISSUE THREAD

**Issue by MIfeanyi** [MIfeanyi/CelestialFreezing#12]
**Describe the bug**
The dialog for the game has options for the following:

- Buy
- Sell
- Cash

**To Reproduce**
1. Abilities to do this are in timelines. There are no store options implemented due to being out of scope.

**Expected behavior**
There should be no store options.

**Screenshots**

**Additional context**
Please remove dialog options. Story rewrite might be needed
- Player was given x, y, or z.
- Someone collected " x ". Here you go main character
- etc

**Comment by MIfeanyi** [comment]
once complete and pushed online please close.

**Comment by Nikorasu97** [comment]
Store options can be implemented through Dialogic's built-in store mechanic. This issue can be closed through the current revamp of CF since development has not reached this stage yet.
